# Generated by Django 2.0.7 on 2018-08-13 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import psych.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('dosage', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PsychDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=psych.models._createId, max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('ethnicity', models.CharField(choices=[('AfA', 'African American'), ('CA', 'Caucasian American'), ('AsA', 'Asian American'), ('HA', 'Hispanic American'), ('ArA', 'Arab American'), ('NA', 'Native American')], max_length=3)),
                ('edu_lvl', models.CharField(choices=[('HS_WO/D', 'Some High School (No Deploma)'), ('HS_W/D', 'High School Deploma'), ('C_WO/D', 'Some College Experience (No Degree)'), ('C_BA', 'Batchelor of Arts'), ('C_BS', 'Batchelor of Science'), ('C_MS', 'Masters Degree'), ('C_DO', 'Doctrate Degree')], max_length=9)),
                ('chronic_desc', models.CharField(blank=True, max_length=155, null=True)),
                ('med_issues', models.ManyToManyField(blank=True, to='psych.MedicalDiagnosis')),
                ('meds', models.ManyToManyField(blank=True, to='psych.Medication')),
                ('mental_issues', models.ManyToManyField(blank=True, to='psych.PsychDiagnosis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id', 'created'),
            },
        ),
    ]
