# Generated by Django 2.0.7 on 2018-09-04 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import psych.models


class Migration(migrations.Migration):

    replaces = [('psych', '0001_initial'), ('psych', '0002_auto_20180813_1757'), ('psych', '0003_auto_20180814_1854'), ('psych', '0004_auto_20180814_1950'), ('psych', '0005_auto_20180817_1211'), ('psych', '0006_test')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('dosage', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PsychDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=psych.models._createId, max_length=16, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('ethnicity', models.CharField(choices=[('AfA', 'African American'), ('CA', 'Caucasian American'), ('AsA', 'Asian American'), ('HA', 'Hispanic American'), ('ArA', 'Arab American'), ('NA', 'Native American')], max_length=3)),
                ('edu_lvl', models.CharField(choices=[('HS_WO/D', 'Some High School (No Diploma)'), ('HS_W/D', 'High School Diploma'), ('C_WO/D', 'Some College Experience (No Diploma)'), ('C_BA', 'Bachelor of Arts'), ('C_BS', 'Bachelor of Science'), ('C_MS', "Master's Degree"), ('C_DO', 'Doctorate Degree')], max_length=9)),
                ('chronic_desc', models.CharField(blank=True, max_length=155, null=True)),
                ('med_issues', models.ManyToManyField(blank=True, to='psych.MedicalDiagnosis')),
                ('meds', models.ManyToManyField(blank=True, to='psych.Medication')),
                ('mental_issues', models.ManyToManyField(blank=True, to='psych.PsychDiagnosis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='medicaldiagnosis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='psychdiagnosis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('test_type', models.CharField(default='PNMT', max_length=45)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Distributed', max_length=12)),
                ('completed', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='psych.Subject')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
