# Generated by Django 2.0.7 on 2018-08-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psych', '0003_auto_20180814_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='edu_lvl',
            field=models.CharField(choices=[('HS_WO/D', 'Some High School (No Diploma)'), ('HS_W/D', 'High School Diploma'), ('C_WO/D', 'Some College Experience (No Diploma)'), ('C_BA', 'Bachelor of Arts'), ('C_BS', 'Bachelor of Science'), ('C_MS', "Master's Degree"), ('C_DO', 'Doctorate Degree')], max_length=9),
        ),
    ]
