# Generated by Django 2.0.7 on 2018-09-04 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('nvmt', '0001_initial'), ('nvmt', '0002_auto_20180725_1225'), ('nvmt', '0003_auto_20180813_1512'), ('nvmt', '0004_test_subject'), ('nvmt', '0005_auto_20180814_1854'), ('nvmt', '0006_remove_test_user'), ('nvmt', '0007_auto_20180814_1900'), ('nvmt', '0008_auto_20180817_1211'), ('nvmt', '0009_auto_20180817_1214'), ('nvmt', '0010_auto_20180817_1215'), ('nvmt', '0011_card_card_num'), ('nvmt', '0012_test_completed'), ('nvmt', '0013_auto_20180817_1826'), ('nvmt', '0014_test_test_type'), ('nvmt', '0015_test_status'), ('nvmt', '0016_auto_20180829_1352'), ('nvmt', '0017_auto_20180829_1359')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psych', '0006_test'),
        ('psych', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('education', models.CharField(choices=[('HS', 'High School'), ('A', 'Associate Degree'), ('B', 'Bachelors Degree'), ('MS', 'Masters'), ('MD', 'Doctor of Medicin'), ('P', 'PhD')], default='HS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvmt.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_num', models.IntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='nvmt.Test')),
            ],
            options={
                'ordering': ['trial_num'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ManyToManyField(to='nvmt.User'),
        ),
        migrations.AddField(
            model_name='card',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='nvmt.Trial'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('is_goal', models.BooleanField(default=False)),
                ('click_time', models.DurationField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='nvmt.Card')),
            ],
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='trial',
            unique_together={('test', 'trial_num')},
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AddField(
            model_name='test',
            name='test_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='nvmt.Test'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='card',
            name='start',
        ),
        migrations.AddField(
            model_name='card',
            name='card_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(default='PNMT', max_length=45),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(default='Distributed', max_length=12),
        ),
        migrations.CreateModel(
            name='NvmtTest',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psych.Test')),
            ],
            bases=('psych.test',),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='psych.Test'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='trial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='nvmt.NvmtTest'),
        ),
    ]
