# Generated by Django 2.0.7 on 2018-07-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('is_goal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('clicked_at', models.DateTimeField(blank=True)),
                ('click_time', models.DurationField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='card',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['trial_num']},
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AlterField(
            model_name='card',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='nvmt.Trial'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='nvmt.Subject'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='nvmt.Test'),
        ),
        migrations.AlterUniqueTogether(
            name='trial',
            unique_together={('test', 'trial_num')},
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.AddField(
            model_name='target',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='nvmt.Card'),
        ),
    ]
