# Generated by Django 2.0.7 on 2018-08-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0002_auto_20180725_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
