# Generated by Django 2.0.7 on 2018-08-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psych', '0001_initial'),
        ('nvmt', '0003_auto_20180813_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='psych.Subject'),
            preserve_default=False,
        ),
    ]
