# Generated by Django 2.0.7 on 2018-08-14 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nvmt', '0004_test_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AddField(
            model_name='test',
            name='test_code',
            field=models.CharField(default=None, max_length=13, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
