# Generated by Django 2.0.7 on 2018-08-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0006_remove_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='nvmt.Trial'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='nvmt.Test'),
        ),
    ]
