# Generated by Django 2.0.7 on 2018-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0007_auto_20180814_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='finish',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
