# Generated by Django 2.0.7 on 2018-08-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0008_auto_20180817_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='card',
            name='start',
        ),
    ]
