# Generated by Django 2.0.7 on 2018-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0009_auto_20180817_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='clicked_at',
        ),
        migrations.RemoveField(
            model_name='target',
            name='created_at',
        ),
    ]
