# Generated by Django 2.0.7 on 2018-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0010_auto_20180817_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_num',
            field=models.IntegerField(default=1),
        ),
    ]
