# Generated by Django 2.0.7 on 2018-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0011_card_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
