# Generated by Django 2.0.7 on 2018-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0013_auto_20180817_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(default='PNMT', max_length=45),
        ),
    ]
