# Generated by Django 2.0.7 on 2018-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0014_test_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(default='Distributed', max_length=12),
        ),
    ]
