# Generated by Django 2.0.7 on 2018-08-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psych', '0006_test'),
        ('nvmt', '0015_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NvmtTest',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psych.Test')),
            ],
            bases=('psych.test',),
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.AlterField(
            model_name='trial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='psych.Test'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
