# Generated by Django 2.0.7 on 2018-08-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvmt', '0016_auto_20180829_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='nvmt.NvmtTest'),
        ),
    ]
